# Generated by Django 4.0.5 on 2022-07-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idPromocion', models.IntegerField(primary_key=True, serialize=False)),
                ('porc_descuento', models.IntegerField()),
                ('fecha_caducidad', models.CharField(max_length=250)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardin.producto')),
            ],
        ),
    ]
